# Create environment:
# % conda env create -f environment.yml
#
# Update environment when there is change:
# % conda env update -f environment.yml --prune
#
# Remove environment:
# % conda remove --name dl --all
#
# Frequently used commands:
# % conda env list
# % conda activate [env name: dl]
# % conda deactivate
# % pip list
# % pip freeze > requirements.txt
# % pip install -r requirements.txt
name: dl
channels:
  - defaults
dependencies:
  - pip
  - python=3.10
  - Cython
  - pip:
      - --requirement requirements.txt